return {
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "stylua",
        "selene",
        "luacheck",
        "shellcheck",
        "shfmt",
        "tailwindcss-language-server",
        "typescript-language-server",
        "css-lsp",
        "omnisharp",
        "eslint-lsp",
        "html-lsp",
        "svelte-language-server",
        "angular-language-server",
        "graphql-language-service-cli",
        "emmet-ls",
        "prisma-language-server",
        "pyright",
        "ruff",
        "json-lsp",
        "yaml-language-server",
      },
    },
  },
  {
    "mason-org/mason-lspconfig.nvim",
    opts = {
      ensure_installed = {
        "lua_ls",
        "ts_ls",
        "cssls",
        "omnisharp",
        "eslint",
        "html",
        "svelte",
        "angularls",
        "graphql",
        "emmet_ls",
        "prismals",
        "pyright",
        "jsonls",
        "yamlls",
      },
    },
  },
}
